= 安装指南



== 安装 Nim

Nim 为三大主流操作系统提供了现成的发行版，安装 Nim 时有多种选择方案。

您可以按照  https://nim-lang.org/install.html[官方安装流程] 来安装最新的稳定版本，或者使用名为 https://github.com/nim-lang/choosenim[choosenim] 的工具——如果您对最新功能和修复感兴趣，它能帮助您轻松切换稳定版和开发版。

无论选择哪种方式，只需按照对应链接中的安装说明操作，Nim 即可完成安装。我们将在后续章节中验证安装是否成功。

若您使用 Linux 系统，您的发行版很可能已通过包管理器收录 Nim。
若采用以上方式安装，请确保获取的是最新版本（可参照官网确认最新版本号），否则请通过上述两种方法之一进行安装。
In this tutorial we will use the stable version.
Originally, this tutorial was written for Nim 0.19 (released in September 2018), and it should work for any newer version, including Nim 1.x and Nim 2.x.
在本教程中，我们将使用稳定版本。
最初，本教程是为 Nim 0.19（2018 年 9 月发布）编写的，它应该适用于任何更新的版本，包括 Nim 1.x 和 Nim 2.x。
（译者注：截止到2025-06-13，nim官网展示的安装版本是2.2.4。有消息称nim3作为实验分支正在开发中）


== Installing additional tools

You can write Nim code in any text editor, and then compile and run it from the terminal.
If you want syntax highlighting and code completion there are plugins for popular code editors which provide these features.

Most of Nim users prefer the https://code.visualstudio.com/[VS Code] editor, with the https://marketplace.visualstudio.com/items?itemName=NimLang.nimlang[Nim extension] which provides syntax highlighting and code completion, and the https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner[Code Runner extension] for quick compiling and running.

The author personally uses https://neovim.io/[NeoVim] editor, with https://github.com/alaviss/nim.nvim[this plugin] which provides additional features like syntax highlighting and code completion.

If you're using other code editors, see https://github.com/nim-lang/Nim/wiki/Editor-Support[the wiki] for available editor support.




== Testing the installation

To check if the installation was successful, we will write a program which is traditionally used as an introductory example: https://en.wikipedia.org/wiki/%22Hello,_World!%22_program[Hello World].

Printing (as in: displaying on the screen; not on a paper with a printer) the phrase `Hello World!` in Nim is straightforward and it doesn't require any boilerplate code.

In a new text file called e.g. `helloworld.nim` we need to write just one line of code:

[source]
.helloworld.nim
----
include::code/helloworld.nim[]
----

NOTE: The phrase you want to print must follow the `echo` command and must be enclosed in double-quotes (`"`).

First we need to compile our program, and then run it to see if it works as expected.

Open your terminal in the same directory where your file is (on Linux you can get "Open Terminal here" if you right-click the directory in your file manager, on Windows you should use Shift + right-click to get the menu option for opening the command line).

We compile our program by typing in the terminal:
[source, terminal]
----
nim c helloworld.nim
----

After a successful compilation, we can run our program.
On Linux we can run our program by typing `./helloworld` in the terminal, and on Windows we do it by typing `helloworld.exe`.

There is also a possibility to both compile and run the program with just one command.
We need to type:
[source, terminal]
----
nim c -r helloworld.nim
----

NOTE: `c` is telling Nim to compile the file, and `-r` is telling it to run it immediately. +
To see all compiler options, type `nim --help` in your terminal.

If you're using VSCode with the Code Runner extension mentioned before, you'll just have to press `Ctrl+Alt+N` and your file will be compiled and run.

Whichever way you chose to run your program, after a brief moment in the output window (or in your terminal) you should see:
[source, output]
----
Hello World!
----

Congratulations, you have successfully run your first Nim program!

Now you know how to print some stuff on the screen (using the `echo` command), compile your program (typing `nim c programName.nim` in your terminal), and run it (various possibilities).

We can now start to explore the basic elements which will help us to write simple Nim programs.
